#!/bin/bash
# TextFlash Release — 生产发布
# 流程：测试 → 注入版本 → release 编译 → 去除符号 → 组装 → 签名 → DMG → 烟测 → 可选发布
# 用法: ./release.sh <version> [--publish] [--allow-dirty]
#   ./release.sh 0.1.12              # 仅构建 DMG
#   ./release.sh 0.1.12 --publish    # 构建 + 推 tag + 创建 GitHub Release
#   ./release.sh --auto-version      # 自动计算版本，仅构建本地 DMG
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="TextFlash"
BUILD_DIR="$PROJECT_DIR/.build/release"
STAGING="$PROJECT_DIR/.release_staging"
RESOURCE_DIR="$PROJECT_DIR/Sources/TextFlash/Resources"
DIST_DIR="$PROJECT_DIR/dist"
BUNDLE_ID="com.nekutai.textflash"
IDENTITY="${CODESIGN_IDENTITY:-Nekutai}"
cd "$PROJECT_DIR"

# 解析参数
PUBLISH=false
ALLOW_DIRTY=false
AUTO_VERSION=false
VERSION=""
for arg in "$@"; do
    case "$arg" in
        --publish) PUBLISH=true ;;
        --allow-dirty) ALLOW_DIRTY=true ;;
        --auto-version) AUTO_VERSION=true ;;
        --*) echo "❌ 未知参数: $arg" >&2; exit 2 ;;
        *)
            [[ -z "$VERSION" ]] || { echo "❌ 只能指定一个版本号" >&2; exit 2; }
            VERSION="$arg"
            ;;
    esac
done
if $AUTO_VERSION; then
    [[ -z "$VERSION" ]] || { echo "❌ --auto-version 不能与显式版本同时使用" >&2; exit 2; }
    $PUBLISH && { echo "❌ 正式发布必须显式确认版本号，不能使用 --auto-version" >&2; exit 2; }
    VERSION="$($PROJECT_DIR/scripts/next_version.sh)"
fi
if [[ -z "$VERSION" ]]; then
    echo "用法: ./release.sh <x.y.z> [--publish] [--allow-dirty] | ./release.sh --auto-version" >&2
    exit 2
fi
VERSION="${VERSION#v}"   # 统一剥掉 v 前缀，内部只用裸版本号
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "❌ 版本号必须是 x.y.z" >&2; exit 2; }
TAG="v$VERSION"
BUILD=$(git rev-list --count HEAD)
DMG_NAME="${APP_NAME}-${VERSION}.dmg"
DMG_PATH="$DIST_DIR/$DMG_NAME"
CHECKSUM_PATH="$DMG_PATH.sha256"
project_dir="$PROJECT_DIR"
source "$PROJECT_DIR/scripts/lib/command_log.sh"
WORKFLOW="release"
$PUBLISH && WORKFLOW="publish"
command_log_init "$WORKFLOW" "$VERSION"

echo "🏭 Building $APP_NAME $VERSION (release)..."
echo ""

step() {
    echo ""
    echo "━━━ $1/8 $2 ━━━"
    command_log_stage "$1-$2"
}

cleanup() {
    local status=$?
    if [ -n "${DMG_DEVICE:-}" ]; then
        hdiutil detach "$DMG_DEVICE" -quiet 2>/dev/null || true
    elif [ -n "${DMG_VOLUME:-}" ] && [ -d "$DMG_VOLUME" ]; then
        hdiutil detach "$DMG_VOLUME" -force >/dev/null 2>&1 || true
    fi
    if [ -n "${SMOKE_VOLUME:-}" ] && [ -d "$SMOKE_VOLUME" ]; then
        hdiutil detach "$SMOKE_VOLUME" -force >/dev/null 2>&1 || true
    fi
    rm -rf "$STAGING"
    mkdir -p "$PROJECT_DIR/Sources/TextFlash/Generated"
    printf '%s\n' \
        '// Auto-generated by release.sh — do not edit' \
        'enum AppVersion {' \
        '    static let current = "0.0.0-dev"' \
        '    static let build = "0"' \
        '}' > "$PROJECT_DIR/Sources/TextFlash/Generated/Version.generated.swift"
    command_log_finish "$status"
}
trap cleanup EXIT

# ── 检查：正式发布边界 ───
if $PUBLISH && $ALLOW_DIRTY; then
    echo "❌ --allow-dirty 只能用于本地制品验收，不能用于正式发布。"
    exit 1
fi
if [ -n "$(git status --porcelain)" ] && ! $ALLOW_DIRTY; then
    echo "❌ 工作区有未提交改动。请先提交。"
    exit 1
fi
if [ "$IDENTITY" = "-" ] || ! security find-identity -v -p codesigning | grep -Fq "\"$IDENTITY\""; then
    echo "❌ 找不到稳定代码签名身份：$IDENTITY；不会回退为 ad-hoc。"
    exit 1
fi
if git rev-parse --verify --quiet "refs/tags/$TAG" >/dev/null; then
    echo "❌ 本地版本标签已存在：$TAG"
    exit 1
fi
if $PUBLISH; then
    CURRENT_BRANCH=$(git branch --show-current)
    [ "$CURRENT_BRANCH" = "main" ] || { echo "❌ 发布必须在 main 分支执行。"; exit 1; }
    command -v gh >/dev/null || { echo "❌ 缺少 gh CLI" >&2; exit 1; }
    git remote get-url origin >/dev/null 2>&1 || { echo "❌ 缺少 Git 远端 origin" >&2; exit 1; }
    command_log_run gh_auth_status gh auth status
    REPOSITORY="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
    command_log_run remote_connectivity git ls-remote origin >/dev/null
    if git ls-remote --tags origin "refs/tags/$TAG" | grep -q .; then
        echo "❌ 远端版本标签已存在：$TAG"
        exit 1
    fi
    if gh release view "$TAG" --repo "$REPOSITORY" >/dev/null 2>&1; then
        echo "❌ GitHub Release 已存在：$TAG；拒绝覆盖正式制品。"
        exit 1
    fi
fi

step 1 "统一验证"
command_log_run mise_check mise run check
if [ -n "$(git status --porcelain)" ] && ! $ALLOW_DIRTY; then
    echo "❌ 验证过程改变了工作区，停止发布。"
    exit 1
fi

step 2 "注入版本号"
mkdir -p "$PROJECT_DIR/Sources/TextFlash/Generated"

cat > "$PROJECT_DIR/Sources/TextFlash/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "$VERSION"
    static let build = "$BUILD"
}
SWIFT
echo "✅ 版本号已注入: $VERSION (build $BUILD)"

step 3 "Release 编译"
rm -rf "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle"
command_log_run swift_release_build swift build -c release -Xswiftc -Osize -Xswiftc -DDISABLE_PREVIEWS

BIN="$BUILD_DIR/$APP_NAME"
test -f "$BIN" || { echo "❌ 构建失败"; exit 1; }
RESOURCE_BUNDLE="$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle"

step 4 "去除调试符号"
BIN_SIZE_BEFORE=$(stat -f%z "$BIN")
command_log_run strip_binary strip -S "$BIN"
BIN_SIZE_AFTER=$(stat -f%z "$BIN")
echo "✅ 二进制已去除调试符号: $(numfmt --to=iec $BIN_SIZE_BEFORE 2>/dev/null || echo "${BIN_SIZE_BEFORE}") → $(numfmt --to=iec $BIN_SIZE_AFTER 2>/dev/null || echo "${BIN_SIZE_AFTER}")"

step 5 "组装 .app bundle"
rm -rf "$STAGING"
mkdir -p "$STAGING/$APP_NAME.app/Contents/MacOS"
mkdir -p "$STAGING/$APP_NAME.app/Contents/Resources"

# 二进制
cp "$BIN" "$STAGING/$APP_NAME.app/Contents/MacOS/$APP_NAME"

# 资源
if [ -f "$RESOURCE_DIR/Assets/AppIcon.icns" ]; then
    cp "$RESOURCE_DIR/Assets/AppIcon.icns" "$STAGING/$APP_NAME.app/Contents/Resources/AppIcon.icns"
fi
if [ -d "$RESOURCE_BUNDLE" ]; then
    cp -R "$RESOURCE_BUNDLE" "$STAGING/$APP_NAME.app/Contents/Resources/"
fi
if [ -d "$RESOURCE_DIR/Tools" ]; then
    cp -R "$RESOURCE_DIR/Tools" "$STAGING/$APP_NAME.app/Contents/Resources/Tools"
    chmod +x "$STAGING/$APP_NAME.app/Contents/Resources/Tools/"*.sh
fi

# Info.plist
cat > "$STAGING/$APP_NAME.app/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleVersion</key>
    <string>$BUILD</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>TextFlash 需要辅助功能权限以监听键盘事件并展开文本。</string>
    <key>NSAccessibilityUsageDescription</key>
    <string>TextFlash 需要辅助功能权限以监听键盘事件并展开文本。</string>
</dict>
</plist>
PLIST
echo "✅ .app bundle 已组装: $STAGING/$APP_NAME.app"

step 6 "代码签名"

# 固定作者级证书签名 = TCC/Accessibility 授权持久保留
# 默认使用 Nekutai；通过 CODESIGN_IDENTITY 环境变量指定其他自签名或开发者账号证书。
if [ "$IDENTITY" = "-" ]; then
    echo "❌ TextFlash 需要稳定代码签名以保留辅助功能授权，不能使用 ad-hoc 签名。"
    echo "   请创建自签名代码签名证书，或设置 CODESIGN_IDENTITY 为开发者账号证书。"
    exit 1
fi
echo "🔐 签名身份: $IDENTITY"

# 公证提醒（需要付费开发者账号）
# 有账号后加一行：
#   xcrun notarytool submit "$DMG_PATH" --keychain-profile "AC_PASSWORD" --wait

if ! command_log_run codesign_app codesign --force --deep --sign "$IDENTITY" "$STAGING/$APP_NAME.app"; then
    echo "❌ \"$IDENTITY\" 签名失败。TextFlash 不会改用 ad-hoc，因为这会破坏辅助功能授权体验。"
    echo "   请检查钥匙串中是否存在该代码签名证书，或通过 CODESIGN_IDENTITY 指定稳定证书。"
    exit 1
fi
command_log_run verify_release "$PROJECT_DIR/scripts/verify_release.sh" "$STAGING/$APP_NAME.app" "$VERSION"

step 7 "DMG 打包和烟测"
mkdir -p "$DIST_DIR"
rm -f "$DMG_PATH" "$CHECKSUM_PATH"

# 创建临时 DMG 目录
DMG_SRC="$STAGING/dmg_root"
mkdir -p "$DMG_SRC"
cp -R "$STAGING/$APP_NAME.app" "$DMG_SRC/"
ln -s /Applications "$DMG_SRC/Applications" 2>/dev/null || true
mkdir -p "$DMG_SRC/.background"
cp "$PROJECT_DIR/Resources/dmg-background.png" "$DMG_SRC/.background/background.png"
cp "$PROJECT_DIR/Resources/dmg-background@2x.png" "$DMG_SRC/.background/background@2x.png"
if command -v SetFile >/dev/null 2>&1; then
    SetFile -a V "$DMG_SRC/.background"
fi

# 计算 DMG 大小
DMG_SIZE_KB=$(du -sk "$DMG_SRC" | cut -f1)
DMG_SIZE_MB=$(( (DMG_SIZE_KB + 1023) / 1024 + 8 ))

command_log_run hdiutil_create hdiutil create -volname "$APP_NAME" \
    -srcfolder "$DMG_SRC" \
    -ov -format UDRW \
    -size ${DMG_SIZE_MB}m \
    "$STAGING/tmp.dmg"

# DMG 美化（挂载最终可写镜像，由 Finder 现场生成与当前卷匹配的布局）
echo "🎨 美化 DMG..."

DMG_VOLUME="$STAGING/dmg-mount"
mkdir -p "$DMG_VOLUME"
if ! command_log_run hdiutil_attach_writable hdiutil attach "$STAGING/tmp.dmg" \
    -readwrite -noverify -noautoopen -mountpoint "$DMG_VOLUME"; then
    echo "❌ DMG 美化挂载失败"
    exit 1
fi
command_log_run layout_dmg osascript "$PROJECT_DIR/scripts/layout_dmg.applescript" "$DMG_VOLUME" "$APP_NAME"
[ -f "$DMG_VOLUME/.DS_Store" ] || { echo "❌ Finder 未生成 DMG 布局记录"; exit 1; }
[ -f "$DMG_VOLUME/.background/background.png" ] || { echo "❌ DMG 背景文件缺失"; exit 1; }
sync

# 卸载
if ! command_log_run hdiutil_detach_writable hdiutil detach "$DMG_VOLUME" -quiet; then
    echo "❌ DMG 美化后卸载失败: $DMG_VOLUME"
    exit 1
fi
DMG_VOLUME=""
echo "✅ DMG 背景和窗口布局已写入"

# 转换为只读压缩 DMG
if ! command_log_run hdiutil_convert hdiutil convert "$STAGING/tmp.dmg" -format UDZO -o "$DMG_PATH"; then
    echo "❌ DMG 压缩转换失败"
    exit 1
fi
rm -f "$STAGING/tmp.dmg"
echo "✅ DMG 已生成: $DMG_PATH"
command_log_run hdiutil_verify hdiutil verify "$DMG_PATH"
shasum -a 256 "$DMG_PATH" > "$CHECKSUM_PATH"
command_log_artifact dmg "$DMG_PATH"
command_log_artifact checksum "$CHECKSUM_PATH"
command_log_run release_smoke "$PROJECT_DIR/scripts/release_smoke.sh" "$DMG_PATH" "$VERSION"

if $PUBLISH; then
    step 8 "发布到 GitHub Releases"
    RELEASE_NOTES_PATH="$STAGING/release-notes.md"
    "$PROJECT_DIR/scripts/generate_release_notes.sh" > "$RELEASE_NOTES_PATH"
    git tag -a "$TAG" -m "$APP_NAME $VERSION"
    if ! command_log_run git_push_atomic git push --atomic origin "HEAD:refs/heads/main" "refs/tags/$TAG"; then
        git tag -d "$TAG" >/dev/null
        echo "❌ 源码分支与版本标签推送失败，本地标签已回滚。" >&2
        exit 1
    fi
    if ! command_log_run gh_release_create gh release create "$TAG" \
        --repo "$REPOSITORY" --notes-file "$RELEASE_NOTES_PATH" --title "$APP_NAME $VERSION" \
        "$DMG_PATH" "$CHECKSUM_PATH"; then
        git push origin ":refs/tags/$TAG" >/dev/null 2>&1 || true
        git tag -d "$TAG" >/dev/null
        echo "❌ GitHub Release 创建失败，本轮版本标签已回滚；已推送的源码分支保留。" >&2
        exit 1
    fi
    echo "✅ 发布完成"
    command_log_run gh_release_url gh release view "$TAG" --repo "$REPOSITORY" --json url --jq .url
else
    step 8 "跳过 GitHub Releases 发布"
    echo "ℹ️  未传入 --publish，仅生成本地 DMG。"
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║  ✅ Release $VERSION 完成              ║"
echo "╠══════════════════════════════════════╣"
printf "║  📦 %-32s ║\n" "$DMG_NAME"
DMG_SIZE=$(stat -f%z "$DMG_PATH" 2>/dev/null || echo 0)
DMG_MB=$((DMG_SIZE / 1048576))
printf "║  📏 DMG: %d MB                        ║\n" $DMG_MB
DMG_SHA=$(awk '{print $1}' "$CHECKSUM_PATH")
printf "║  🔐 SHA256: %.23s…        ║\n" "$DMG_SHA"
echo "╚══════════════════════════════════════╝"
echo "SHA256 ($DMG_NAME): $DMG_SHA"
echo "校验文件: $CHECKSUM_PATH"
