#!/bin/bash
# TextFlash Release — 生产发布
# 流程：测试 → 注入版本 → release 编译 → 去除符号 → 组装 → 签名 → DMG → 烟测 → 可选发布
# 用法: ./release.sh [version] [--publish]
#   ./release.sh 0.1.12              # 仅构建 DMG
#   ./release.sh 0.1.12 --publish    # 构建 + 推 tag + 创建 GitHub Release
#   ./release.sh                     # 自动取 git tag，没有则用 0.1.0
set -e
set -o pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="TextFlash"
BUILD_DIR="$PROJECT_DIR/.build/release"
STAGING="$PROJECT_DIR/.release_staging"
RESOURCE_DIR="$PROJECT_DIR/Sources/TextFlash/Resources"
DIST_DIR="$PROJECT_DIR/dist"
BUNDLE_ID="com.nekutai.textflash"
IDENTITY="${CODESIGN_IDENTITY:-Nekutai}"

# 解析参数
PUBLISH=false
FORCE=false
VERSION=""
for arg in "$@"; do
    case "$arg" in
        --publish) PUBLISH=true ;;
        --force) FORCE=true ;;
        --*) ;;
        *) VERSION="$arg" ;;
    esac
done
VERSION="${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo '0.1.0')}"
VERSION="${VERSION#v}"   # 统一剥掉 v 前缀，内部只用裸版本号
TAG="v$VERSION"
BUILD=$(git rev-list --count HEAD)
DMG_NAME="${APP_NAME}-${VERSION}.dmg"

echo "🏭 Building $APP_NAME $VERSION (release)..."
echo ""

step() {
    echo ""
    echo "━━━ $1/8 $2 ━━━"
}

# ── 检查：发布输入状态（--force 跳过）───
if [ -n "$(git status --porcelain)" ] && ! $FORCE; then
    echo "❌ 工作区有未提交改动。请先提交，或使用 --force 明确跳过。"
    exit 1
fi

EXISTING_TAG=$(git tag --points-at HEAD | head -1)
if [ -n "$EXISTING_TAG" ] && [ "$EXISTING_TAG" != "$TAG" ] && ! $FORCE; then
    echo "❌ 当前 commit 已有 tag \"$EXISTING_TAG\"，没有新代码"
    echo "ℹ️  如需强制重新发布：先 commit 改动后再运行"
    exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)
if $PUBLISH && [ "$CURRENT_BRANCH" != "main" ] && ! $FORCE; then
    echo "❌ 当前分支是 \"$CURRENT_BRANCH\"，发布必须在 main 分支执行。"
    echo "ℹ️  如需强制发布：使用 --force。"
    exit 1
fi

cd "$PROJECT_DIR"

cleanup() {
    if [ -n "${DMG_DEVICE:-}" ]; then
        hdiutil detach "$DMG_DEVICE" -quiet 2>/dev/null || true
    elif [ -n "${DMG_VOLUME:-}" ] && [ -d "$DMG_VOLUME" ]; then
        hdiutil detach "$DMG_VOLUME" -quiet 2>/dev/null || true
    fi
    if [ -n "${SMOKE_VOLUME:-}" ] && [ -d "$SMOKE_VOLUME" ]; then
        hdiutil detach "$SMOKE_VOLUME" -quiet 2>/dev/null || true
    fi
    rm -rf "$STAGING"
    cat > "$PROJECT_DIR/Sources/TextFlash/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "0.0.0-dev"
    static let build = "0"
}
SWIFT
}

step 1 "测试"
# 自动检测：无 Xcode 则跳过测试（XCTest/Testing 框架需要完整 Xcode）
RUN_TESTS="${RUN_TESTS:-}"
if [ "$RUN_TESTS" = "" ]; then
    if xcode-select -p 2>/dev/null | grep -q "/Xcode.app/"; then
        RUN_TESTS=true
    else
        RUN_TESTS=false
        echo "⚠️  未检测到 Xcode，自动跳过测试（XCTest/Testing 框架需要完整 Xcode）"
    fi
fi
if [ "$RUN_TESTS" = "true" ]; then
    swift test -Xswiftc -DDISABLE_PREVIEWS 2>&1 | tail -5
else
    echo "⚠️  跳过测试"
fi

step 2 "注入版本号"
mkdir -p "$PROJECT_DIR/Sources/TextFlash/Generated"
trap cleanup EXIT

cat > "$PROJECT_DIR/Sources/TextFlash/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "$VERSION"
    static let build = "$BUILD"
}
SWIFT
echo "✅ 版本号已注入: $VERSION (build $BUILD)"

step 3 "Release 编译"
rm -rf "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle"
swift build -c release -Xswiftc -Osize -Xswiftc -DDISABLE_PREVIEWS 2>&1 | tail -3

BIN="$BUILD_DIR/$APP_NAME"
test -f "$BIN" || { echo "❌ 构建失败"; exit 1; }
RESOURCE_BUNDLE="$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle"

step 4 "去除调试符号"
BIN_SIZE_BEFORE=$(stat -f%z "$BIN")
strip -S "$BIN" 2>/dev/null || true
BIN_SIZE_AFTER=$(stat -f%z "$BIN")
echo "✅ 二进制已去除调试符号: $(numfmt --to=iec $BIN_SIZE_BEFORE 2>/dev/null || echo "${BIN_SIZE_BEFORE}") → $(numfmt --to=iec $BIN_SIZE_AFTER 2>/dev/null || echo "${BIN_SIZE_AFTER}")"

step 5 "组装 .app bundle"
rm -rf "$STAGING"
mkdir -p "$STAGING/$APP_NAME.app/Contents/MacOS"
mkdir -p "$STAGING/$APP_NAME.app/Contents/Resources"

# 二进制
cp "$BIN" "$STAGING/$APP_NAME.app/Contents/MacOS/$APP_NAME"

# 资源
if [ -f "$RESOURCE_DIR/Assets/AppIcon.icns" ]; then
    cp "$RESOURCE_DIR/Assets/AppIcon.icns" "$STAGING/$APP_NAME.app/Contents/Resources/AppIcon.icns"
fi
if [ -d "$RESOURCE_BUNDLE" ]; then
    cp -R "$RESOURCE_BUNDLE" "$STAGING/$APP_NAME.app/Contents/Resources/"
fi
if [ -d "$RESOURCE_DIR/Tools" ]; then
    cp -R "$RESOURCE_DIR/Tools" "$STAGING/$APP_NAME.app/Contents/Resources/Tools"
    chmod +x "$STAGING/$APP_NAME.app/Contents/Resources/Tools/"*.sh
fi

# Info.plist
cat > "$STAGING/$APP_NAME.app/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleVersion</key>
    <string>$BUILD</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>TextFlash 需要辅助功能权限以监听键盘事件并展开文本。</string>
    <key>NSAccessibilityUsageDescription</key>
    <string>TextFlash 需要辅助功能权限以监听键盘事件并展开文本。</string>
</dict>
</plist>
PLIST
echo "✅ .app bundle 已组装: $STAGING/$APP_NAME.app"

step 6 "代码签名"

# 固定作者级证书签名 = TCC/Accessibility 授权持久保留
# 默认使用 Nekutai；通过 CODESIGN_IDENTITY 环境变量指定其他自签名或开发者账号证书。
if [ "$IDENTITY" = "-" ]; then
    echo "❌ TextFlash 需要稳定代码签名以保留辅助功能授权，不能使用 ad-hoc 签名。"
    echo "   请创建自签名代码签名证书，或设置 CODESIGN_IDENTITY 为开发者账号证书。"
    exit 1
fi
echo "🔐 签名身份: $IDENTITY"

# 公证提醒（需要付费开发者账号）
# 有账号后加一行：
#   xcrun notarytool submit "$DMG_PATH" --keychain-profile "AC_PASSWORD" --wait

if ! codesign --force --deep --sign "$IDENTITY" "$STAGING/$APP_NAME.app" 2>&1; then
    echo "❌ \"$IDENTITY\" 签名失败。TextFlash 不会改用 ad-hoc，因为这会破坏辅助功能授权体验。"
    echo "   请检查钥匙串中是否存在该代码签名证书，或通过 CODESIGN_IDENTITY 指定稳定证书。"
    exit 1
fi

step 7 "DMG 打包和烟测"
mkdir -p "$DIST_DIR"
DMG_PATH="$DIST_DIR/$DMG_NAME"
rm -f "$DMG_PATH"

# 创建临时 DMG 目录
DMG_SRC="$STAGING/dmg_root"
mkdir -p "$DMG_SRC"
cp -R "$STAGING/$APP_NAME.app" "$DMG_SRC/"
ln -s /Applications "$DMG_SRC/Applications" 2>/dev/null || true

# 计算 DMG 大小
APP_SIZE_KB=$(du -sk "$DMG_SRC/$APP_NAME.app" | cut -f1)
DMG_SIZE_MB=$(( (APP_SIZE_KB / 1024) + 4 ))

hdiutil create -volname "$APP_NAME" \
    -srcfolder "$DMG_SRC" \
    -ov -format UDRW \
    -size ${DMG_SIZE_MB}m \
    "$STAGING/tmp.dmg" 2>&1 | tail -1

# DMG 美化（静默：挂载→拷背景+DS_Store→卸载，无 Finder 闪现）
echo "🎨 美化 DMG..."

# 挂载（-noautoopen 不打开 Finder 窗口）
DMG_ATTACH_LOG="$STAGING/dmg-attach.log"
if ! hdiutil attach -readwrite -noverify -noautoopen "$STAGING/tmp.dmg" > "$DMG_ATTACH_LOG" 2>&1; then
    echo "❌ DMG 美化挂载失败"
    cat "$DMG_ATTACH_LOG"
    exit 1
fi
DMG_DEVICE=$(awk '/\/Volumes\// {print $1; exit}' "$DMG_ATTACH_LOG")
DMG_VOLUME=$(awk '/\/Volumes\// {for (i=3; i<=NF; i++) printf "%s%s", (i==3 ? "" : " "), $i; print ""; exit}' "$DMG_ATTACH_LOG")
VOLUME="${DMG_VOLUME:-/Volumes/$APP_NAME}"
if [ ! -d "$VOLUME" ]; then
    echo "❌ DMG 美化挂载后未找到卷目录: $VOLUME"
    cat "$DMG_ATTACH_LOG"
    exit 1
fi

# 复制背景图（含 Retina @2x）
mkdir -p "$VOLUME/.background"
cp "$PROJECT_DIR/Resources/dmg-background.png" "$VOLUME/.background/background.png" || { echo "❌ 复制 DMG 背景图失败"; exit 1; }
cp "$PROJECT_DIR/Resources/dmg-background@2x.png" "$VOLUME/.background/background@2x.png" || { echo "❌ 复制 DMG Retina 背景图失败"; exit 1; }
if command -v SetFile >/dev/null 2>&1; then
    SetFile -a V "$VOLUME/.background"
fi

# 复制预制的 .DS_Store 模板（窗口大小、图标位置、背景图引用）
cp "$PROJECT_DIR/Resources/dmg-dsstore" "$VOLUME/.DS_Store" || { echo "❌ 复制 DMG .DS_Store 模板失败"; exit 1; }

# 卸载
if ! hdiutil detach "${DMG_DEVICE:-$VOLUME}" -quiet; then
    echo "❌ DMG 美化后卸载失败: ${DMG_DEVICE:-$VOLUME}"
    exit 1
fi
DMG_DEVICE=""
DMG_VOLUME=""
echo "✅ DMG 背景和窗口布局已写入"

# 转换为只读压缩 DMG
CONVERT_LOG="$STAGING/dmg-convert.log"
if ! hdiutil convert "$STAGING/tmp.dmg" -format UDZO -o "$DMG_PATH" > "$CONVERT_LOG" 2>&1; then
    echo "❌ DMG 压缩转换失败"
    cat "$CONVERT_LOG"
    exit 1
fi
tail -1 "$CONVERT_LOG"
rm -f "$STAGING/tmp.dmg"
echo "✅ DMG 已生成: $DMG_PATH"

echo "🧪 烟测 DMG..."
SMOKE_ATTACH_LOG="$STAGING/smoke-attach.log"
if ! hdiutil attach -readonly -noverify -noautoopen "$DMG_PATH" > "$SMOKE_ATTACH_LOG" 2>&1; then
    echo "❌ DMG 烟测挂载失败"
    cat "$SMOKE_ATTACH_LOG"
    exit 1
fi
SMOKE_MOUNT=$(cat "$SMOKE_ATTACH_LOG")
SMOKE_DEVICE=$(echo "$SMOKE_MOUNT" | awk '/\/Volumes\// {print $1; exit}')
SMOKE_VOLUME=$(echo "$SMOKE_MOUNT" | awk '/\/Volumes\// {for (i=3; i<=NF; i++) printf "%s%s", (i==3 ? "" : " "), $i; print ""; exit}')
if [ -z "$SMOKE_VOLUME" ] || [ ! -d "$SMOKE_VOLUME" ]; then
    echo "❌ DMG 烟测挂载失败"
    exit 1
fi

SMOKE_APP="$SMOKE_VOLUME/$APP_NAME.app"
test -d "$SMOKE_APP" || { echo "❌ DMG 内缺少 $APP_NAME.app"; exit 1; }
codesign --verify --deep --strict "$SMOKE_APP" 2>&1
spctl --assess --type execute "$SMOKE_APP" 2>/dev/null || echo "⚠️  Gatekeeper 评估未通过（自签名或未公证签名时预期可能失败）"
hdiutil detach "${SMOKE_DEVICE:-$SMOKE_VOLUME}" -quiet
SMOKE_VOLUME=""

if $PUBLISH; then
    step 8 "发布到 GitHub Releases"

    if ! command -v gh &>/dev/null; then
        echo "❌ 未安装 gh CLI，请先运行: brew install gh && gh auth login"
        exit 1
    fi

    if ! gh auth status &>/dev/null; then
        echo "❌ gh 未登录，请先运行: gh auth login"
        exit 1
    fi

    # 创建 tag 并推送
    if git rev-parse "$TAG" &>/dev/null; then
        echo "⚠️  tag $TAG 已存在，跳过创建"
    else
        echo "🏷  创建 tag $TAG..."
        git tag "$TAG"
    fi

    git push origin main "$TAG" 2>&1 | tail -2

    # 检查是否已有同名 Release
    if gh release view "$TAG" &>/dev/null 2>&1; then
        echo "⚠️  Release $TAG 已存在，仅上传资产..."
        gh release upload "$TAG" "$DMG_PATH" --clobber
    else
        echo "📦 创建 Release $TAG..."

        # 生成更新日志：从上一个 tag 到 HEAD 的 Conventional Commits
        last_tag=$(git describe --tags --abbrev=0 HEAD~ 2>/dev/null || echo "")
        if [[ -n "$last_tag" ]]; then
            changelog=$(git log "${last_tag}..HEAD" --pretty=format:"- %s" --no-merges 2>/dev/null)
            if [[ -z "$changelog" ]]; then
                changelog="- $APP_NAME $VERSION 发布"
            fi
        else
            changelog="- $APP_NAME $VERSION 发布"
        fi

        gh release create "$TAG" \
            --title "$APP_NAME $VERSION" \
            --notes "$changelog" \
            "$DMG_PATH"
    fi

    echo "✅ 发布完成"
    echo "🔗 $(gh release view "$TAG" --json url -q '.url')"
else
    step 8 "跳过 GitHub Releases 发布"
    echo "ℹ️  未传入 --publish，仅生成本地 DMG。"
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║  ✅ Release $VERSION 完成              ║"
echo "╠══════════════════════════════════════╣"
printf "║  📦 %-32s ║\n" "$DMG_NAME"
DMG_SIZE=$(stat -f%z "$DMG_PATH" 2>/dev/null || echo 0)
DMG_MB=$((DMG_SIZE / 1048576))
printf "║  📏 DMG: %d MB                        ║\n" $DMG_MB
DMG_SHA=$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')
printf "║  🔐 SHA256: %.23s…        ║\n" "$DMG_SHA"
echo "╚══════════════════════════════════════╝"
echo "SHA256 ($DMG_NAME): $DMG_SHA"
