name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: mise run check
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show Swift version
        run: swift --version

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: CI
        run: mise run check
